<a href="https://colab.research.google.com/github/rakesh-bestha/AI-ML/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas


In [ ]:
import pandas as pd
print(pd.__version__)

2.2.2


In [ ]:
scores = pd.Series([80, 70.5, 91, 87.5, 73])
print(scores)

0    80.0
1    70.5
2    91.0
3    87.5
4    73.0
dtype: float64


In [ ]:
scores = pd.Series([80, 70.5, 91, 87.5, 73], index = ["Rakesh", "Rajesh", "Cherry", "Sam", "Jim"])
print(scores)

Rakesh    80.0
Rajesh    70.5
Cherry    91.0
Sam       87.5
Jim       73.0
dtype: float64


In [ ]:
scores = pd.Series({
    "Rakesh" : 80,
    "Rajesh" : 70.5,
    "Cherry" : 91,
    "Sam" : 87.5,
    "Jim" : 73
})
print(scores)
print("\n")
scores.values # array([80. , 70.5, 91. , 87.5, 73. ])

scores.index # Index(['Rakesh', 'Rajesh', 'Cherry', 'Sam', 'Jim'], dtype='object')

Rakesh    80.0
Rajesh    70.5
Cherry    91.0
Sam       87.5
Jim       73.0
dtype: float64




Index(['Rakesh', 'Rajesh', 'Cherry', 'Sam', 'Jim'], dtype='object')

In [ ]:
scores = pd.Series({
    "Rakesh" : 80,
    "Rajesh" : 70.5,
    "Cherry" : 91,
    "Sam" : 87.5,
    "Jim" : 73
})

print(scores.sum()) # Adds the values in array
print(scores.mean()) # cal mean of the values
print(scores.min()) # Gives minimum value of the list
print(scores.max()) # Gives maximum value of the list

402.0
80.4
70.5
91.0


In [ ]:
scores.values + 5.4


array([85.4, 75.9, 96.4, 92.9, 78.4])

In [ ]:
scores.values * 2

array([160., 141., 182., 175., 146.])

In [ ]:
scores.values - 7

array([73. , 63.5, 84. , 80.5, 66. ])

In [ ]:
scores > 80

Rakesh    False
Rajesh    False
Cherry     True
Sam        True
Jim       False
dtype: bool

# Dataframe

In [ ]:
df = pd.DataFrame({
    "Name" : ["Rakesh", "Rajesh", "Sam", "Cherry", "Jim"],
    "Age" : [20,21,19,24,20],
    "Score" : [80, 70.5, 91, 87.5, 73],
    "Grade" : ["A", "B", "A", "A", "C"]
})

df


Name  Age  Score Grade
0  Rakesh   20   80.0     A
1  Rajesh   21   70.5     B
2     Sam   19   91.0     A
3  Cherry   24   87.5     A
4     Jim   20   73.0     C

In [ ]:
data = [
    {"Name" : "Rakesh", "Age" : 25 , "Score" : 80, "Grade" : "A"},
    {"Name" : "Carl", "Age" : 22 , "Score" : 72, "Grade" : "B"},
    {"Name" : "Sam", "Age" : 20 , "Score" : 86, "Grade" : "A"},
    {"Name" : "Jim", "Age" : 24 , "Score" : 76, "Grade" : "B"},
]

df = pd. DataFrame(data)
df

Name  Age  Score Grade
0  Rakesh   25     80     A
1    Carl   22     72     B
2     Sam   20     86     A
3     Jim   24     76     B

In [ ]:
data = [
    {"Name" : "Rakesh", "Age" : 25 , "Score" : 80, "Grade" : "A"},
    {"Name" : "Carl", "Age" : 22 , "Score" : 72, "Grade" : "B"},
    {"Name" : "Sam", "Age" : 20 , "Score" : 86, "Grade" : "A"},
    {"Name" : "Jim", "Age" : 24 , "Score" : 76, "Grade1" : "B"},
]

df = pd. DataFrame(data)
df

Name  Age  Score Grade Grade1
0  Rakesh   25     80     A    NaN
1    Carl   22     72     B    NaN
2     Sam   20     86     A    NaN
3     Jim   24     76   NaN      B

In [ ]:
import numpy as np

arr = np.array([
    [20, 88.5],
    [23, 67.8],
    [29, 45.3]
])

df = pd.DataFrame(arr)
df

0     1
0  20.0  88.5
1  23.0  67.8
2  29.0  45.3

In [ ]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [ ]:
arr = np.array([
    [20, 88.5],
    [23, 67.8],
    [29, 45.3]
])

df = pd.DataFrame(arr, columns = ["Age", "Score"], index = ["student1", 2, 5])
df

Age  Score
student1  20.0   88.5
2         23.0   67.8
5         29.0   45.3

In [ ]:
df.shape

(3, 2)

In [ ]:
df.columns

Index(['Age', 'Score'], dtype='object')

In [ ]:
df.index

Index(['student1', 2, 5], dtype='object')

In [ ]:
df.dtypes

Age      float64
Score    float64
dtype: object

In [ ]:
for i in df.columns:
  print(i)
  print(df[i])

Age
student1    20.0
2           23.0
5           29.0
Name: Age, dtype: float64
Score
student1    88.5
2           67.8
5           45.3
Name: Score, dtype: float64


In [ ]:
df["Age"]

student1    20.0
2           23.0
5           29.0
Name: Age, dtype: float64

In [ ]:
df[0] # throws Error to access 0 index data

KeyError: 0

# loc and iloc


In [ ]:
df.iloc[0] # this iloc (IndexLocation) helps to access the indexed data;

Age      20.0
Score    88.5
Name: student1, dtype: float64

In [ ]:
df.iloc[0:2, 1]

student1    88.5
2           67.8
Name: Score, dtype: float64

In [81]:
df = pd.read_csv("/content/Titanic-Dataset.csv")
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [82]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [84]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [85]:
df.shape

(891, 12)